[theme]
primaryColor = "#997950" # Earthy Brown: Inspired by the arid landscape and clay used in architecture
backgroundColor = "#F5F0E1" # Off-White: Mimics the limestone and alabaster used in their buildings and sculptures
secondaryBackgroundColor = "#4666A2" # Lapis Lazuli Blue: Represents the precious stones used in their art
textColor = "#D4AF37" # Deep Gold: Stands out against both blue and brown, representative of gold in their art
font = "serif" # Serif fonts can give a more traditional and historic feel
